// Auto-generated pre-bundled batch data for offline & instant loading
export const DEFAULT_BATCHES = [
  {
    "id": "batch-prarambh-2026",
    "name": "Prarambh 2026 Batch for MBBS 1st Year",
    "subtitle": "Live on PW MedEd APP",
    "sourceUrl": "https://docs.google.com/spreadsheets/d/1o2lcDhROx_alTy2zm2he5b7xSPsnk6UdzxzmTWA5_40/edit?gid=883157297#gid=883157297",
    "gid": "883157297",
    "sheetTabName": "Lecture Planner",
    "lastSynced": "2026-09-14T11:29:06.636Z",
    "eventCount": 46,
    "events": [
      {
        "id": "batch-prarambh-2026_ev_1",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 2,
        "dateRaw": "Thursday, October 15, 2026",
        "isoDate": "2026-10-15",
        "dayName": "Thursday",
        "monthName": "October",
        "dayNumber": 15,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "Introduction and Orientation- Anatomy",
        "topic": "Introduction and Orientation- Anatomy",
        "noLectures": "1",
        "duration": "1 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Introduction and Orientation- Anatomy"
      },
      {
        "id": "batch-prarambh-2026_ev_2",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 3,
        "dateRaw": "Friday, October 16, 2026",
        "isoDate": "2026-10-16",
        "dayName": "Friday",
        "monthName": "October",
        "dayNumber": 16,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "Introduction and Orientation- Physiology",
        "topic": "Introduction and Orientation- Physiology",
        "noLectures": "1",
        "duration": "1 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "Introduction and Orientation- Physiology"
      },
      {
        "id": "batch-prarambh-2026_ev_3",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 4,
        "dateRaw": "Saturday, October 17, 2026",
        "isoDate": "2026-10-17",
        "dayName": "Saturday",
        "monthName": "October",
        "dayNumber": 17,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Introduction and Orientation- Biochemistry",
        "topic": "Introduction and orientation- Biochemistry",
        "noLectures": "1",
        "duration": "1 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Introduction and orientation- Biochemistry"
      },
      {
        "id": "batch-prarambh-2026_ev_4",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 5,
        "dateRaw": "Sunday, October 18, 2026",
        "isoDate": "2026-10-18",
        "dayName": "Sunday",
        "monthName": "October",
        "dayNumber": 18,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      },
      {
        "id": "batch-prarambh-2026_ev_5",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 6,
        "dateRaw": "Monday, October 19, 2026",
        "isoDate": "2026-10-19",
        "dayName": "Monday",
        "monthName": "October",
        "dayNumber": 19,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "General Physiology",
        "topic": "Introduction , Body Fluids ,\n Measurement of Body Fluid Volumes \n Disturbances In Body Fluids",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "Introduction , Body Fluids ,\n Measurement of Body Fluid Volumes \n Disturbances In Body Fluids"
      },
      {
        "id": "batch-prarambh-2026_ev_6",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 7,
        "dateRaw": "Tuesday, October 20, 2026",
        "isoDate": "2026-10-20",
        "dayName": "Tuesday",
        "monthName": "October",
        "dayNumber": 20,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "GENERAL ANATOMY",
        "topic": "Cartilage & Bones",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Cartilage & Bones"
      },
      {
        "id": "batch-prarambh-2026_ev_7",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 8,
        "dateRaw": "Wednesday, October 21, 2026",
        "isoDate": "2026-10-21",
        "dayName": "Wednesday",
        "monthName": "October",
        "dayNumber": 21,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Cell Membrane And Transport",
        "topic": "Fluid Mosaic Model , Passive Transport , Active Transport",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Fluid Mosaic Model , Passive Transport , Active Transport"
      },
      {
        "id": "batch-prarambh-2026_ev_8",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 9,
        "dateRaw": "Thursday, October 22, 2026",
        "isoDate": "2026-10-22",
        "dayName": "Thursday",
        "monthName": "October",
        "dayNumber": 22,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "GENERAL ANATOMY",
        "topic": "Joints",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Joints"
      },
      {
        "id": "batch-prarambh-2026_ev_9",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 10,
        "dateRaw": "Friday, October 23, 2026",
        "isoDate": "2026-10-23",
        "dayName": "Friday",
        "monthName": "October",
        "dayNumber": 23,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "General Physiology",
        "topic": "Body fluid compartments - part 2",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "Body fluid compartments - part 2"
      },
      {
        "id": "batch-prarambh-2026_ev_10",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 11,
        "dateRaw": "Saturday, October 24, 2026",
        "isoDate": "2026-10-24",
        "dayName": "Saturday",
        "monthName": "October",
        "dayNumber": 24,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Enzymes",
        "topic": "Defintion and Classification of Enzymes, Mechanism of enzyme Action",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Defintion and Classification of Enzymes, Mechanism of enzyme Action"
      },
      {
        "id": "batch-prarambh-2026_ev_11",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 12,
        "dateRaw": "Sunday, October 25, 2026",
        "isoDate": "2026-10-25",
        "dayName": "Sunday",
        "monthName": "October",
        "dayNumber": 25,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      },
      {
        "id": "batch-prarambh-2026_ev_12",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 13,
        "dateRaw": "Monday, October 26, 2026",
        "isoDate": "2026-10-26",
        "dayName": "Monday",
        "monthName": "October",
        "dayNumber": 26,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "Cell, Homeostasis",
        "topic": "ICF, ECF , Equilibrium V/S Steady State \nHomeostasis Regulatory Mechanisms",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "ICF, ECF , Equilibrium V/S Steady State \nHomeostasis Regulatory Mechanisms"
      },
      {
        "id": "batch-prarambh-2026_ev_13",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 14,
        "dateRaw": "Tuesday, October 27, 2026",
        "isoDate": "2026-10-27",
        "dayName": "Tuesday",
        "monthName": "October",
        "dayNumber": 27,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "GENERAL ANATOMY",
        "topic": "Joints",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Joints"
      },
      {
        "id": "batch-prarambh-2026_ev_14",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 15,
        "dateRaw": "Wednesday, October 28, 2026",
        "isoDate": "2026-10-28",
        "dayName": "Wednesday",
        "monthName": "October",
        "dayNumber": 28,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Enzymes",
        "topic": "Coenzymes , Factors Affecting Enzyme Activity",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Coenzymes , Factors Affecting Enzyme Activity"
      },
      {
        "id": "batch-prarambh-2026_ev_15",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 16,
        "dateRaw": "Thursday, October 29, 2026",
        "isoDate": "2026-10-29",
        "dayName": "Thursday",
        "monthName": "October",
        "dayNumber": 29,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "SUPERIOR EXTREMITY",
        "topic": "The Pectoral Region",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "The Pectoral Region"
      },
      {
        "id": "batch-prarambh-2026_ev_16",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 17,
        "dateRaw": "Friday, October 30, 2026",
        "isoDate": "2026-10-30",
        "dayName": "Friday",
        "monthName": "October",
        "dayNumber": 30,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "Homeostatic regulatory mechanisms",
        "topic": "Feedback , Feedforward , \nEfficiency of A Feedback Mechanism",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "Feedback , Feedforward , \nEfficiency of A Feedback Mechanism"
      },
      {
        "id": "batch-prarambh-2026_ev_17",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 18,
        "dateRaw": "Saturday, October 31, 2026",
        "isoDate": "2026-10-31",
        "dayName": "Saturday",
        "monthName": "October",
        "dayNumber": 31,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Enzymes",
        "topic": "Competitive Inhibition , Noncompetitive Inhibition , \nUncompetitive Inhibition , Irreversible Inhibition , \nSuicide Inhibition , Feedback Inhibition",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Competitive Inhibition , Noncompetitive Inhibition , \nUncompetitive Inhibition , Irreversible Inhibition , \nSuicide Inhibition , Feedback Inhibition"
      },
      {
        "id": "batch-prarambh-2026_ev_18",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 19,
        "dateRaw": "Sunday, November 1, 2026",
        "isoDate": "2026-11-01",
        "dayName": "Sunday",
        "monthName": "November",
        "dayNumber": 1,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      },
      {
        "id": "batch-prarambh-2026_ev_19",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 20,
        "dateRaw": "Monday, November 2, 2026",
        "isoDate": "2026-11-02",
        "dayName": "Monday",
        "monthName": "November",
        "dayNumber": 2,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "Cell membrane",
        "topic": "Structure , Components , Transport Proteins",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "Structure , Components , Transport Proteins"
      },
      {
        "id": "batch-prarambh-2026_ev_20",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 21,
        "dateRaw": "Tuesday, November 3, 2026",
        "isoDate": "2026-11-03",
        "dayName": "Tuesday",
        "monthName": "November",
        "dayNumber": 3,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "SUPERIOR EXTREMITY",
        "topic": "The Breast",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "The Breast"
      },
      {
        "id": "batch-prarambh-2026_ev_21",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 22,
        "dateRaw": "Wednesday, November 4, 2026",
        "isoDate": "2026-11-04",
        "dayName": "Wednesday",
        "monthName": "November",
        "dayNumber": 4,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Enzymes",
        "topic": "Isoenzymes , Diagnostic Uses of Enzymes",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Isoenzymes , Diagnostic Uses of Enzymes"
      },
      {
        "id": "batch-prarambh-2026_ev_22",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 23,
        "dateRaw": "Thursday, November 5, 2026",
        "isoDate": "2026-11-05",
        "dayName": "Thursday",
        "monthName": "November",
        "dayNumber": 5,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "SUPERIOR EXTREMITY",
        "topic": "The Back & Scapular Region.",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "The Back & Scapular Region."
      },
      {
        "id": "batch-prarambh-2026_ev_23",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 24,
        "dateRaw": "Friday, November 6, 2026",
        "isoDate": "2026-11-06",
        "dayName": "Friday",
        "monthName": "November",
        "dayNumber": 6,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "Transport processes across membrane",
        "topic": "Endocytosis , Exocytosis , Osmosis",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "Endocytosis , Exocytosis , Osmosis"
      },
      {
        "id": "batch-prarambh-2026_ev_24",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 25,
        "dateRaw": "Saturday, November 7, 2026",
        "isoDate": "2026-11-07",
        "dayName": "Saturday",
        "monthName": "November",
        "dayNumber": 7,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Enzymes",
        "topic": "Regulation of Enzyme Activity",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Regulation of Enzyme Activity"
      },
      {
        "id": "batch-prarambh-2026_ev_25",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 26,
        "dateRaw": "Sunday, November 8, 2026",
        "isoDate": "2026-11-08",
        "dayName": "Sunday",
        "monthName": "November",
        "dayNumber": 8,
        "year": 2026,
        "faculty": "Diwali Holidays",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "holiday",
        "displayTitle": "Diwali Holidays"
      },
      {
        "id": "batch-prarambh-2026_ev_26",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 27,
        "dateRaw": "Monday, November 9, 2026",
        "isoDate": "2026-11-09",
        "dayName": "Monday",
        "monthName": "November",
        "dayNumber": 9,
        "year": 2026,
        "faculty": "",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "holiday",
        "displayTitle": "Holiday"
      },
      {
        "id": "batch-prarambh-2026_ev_27",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 28,
        "dateRaw": "Tuesday, November 10, 2026",
        "isoDate": "2026-11-10",
        "dayName": "Tuesday",
        "monthName": "November",
        "dayNumber": 10,
        "year": 2026,
        "faculty": "",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "holiday",
        "displayTitle": "Holiday"
      },
      {
        "id": "batch-prarambh-2026_ev_28",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 29,
        "dateRaw": "Wednesday, November 11, 2026",
        "isoDate": "2026-11-11",
        "dayName": "Wednesday",
        "monthName": "November",
        "dayNumber": 11,
        "year": 2026,
        "faculty": "",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "holiday",
        "displayTitle": "Holiday"
      },
      {
        "id": "batch-prarambh-2026_ev_29",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 30,
        "dateRaw": "Thursday, November 12, 2026",
        "isoDate": "2026-11-12",
        "dayName": "Thursday",
        "monthName": "November",
        "dayNumber": 12,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "SUPERIOR EXTREMITY",
        "topic": "Bones - Clavicle, Scapula, Humerus.",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Bones - Clavicle, Scapula, Humerus."
      },
      {
        "id": "batch-prarambh-2026_ev_30",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 31,
        "dateRaw": "Friday, November 13, 2026",
        "isoDate": "2026-11-13",
        "dayName": "Friday",
        "monthName": "November",
        "dayNumber": 13,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "Transport processes",
        "topic": "Diffusion Types , Factors Influencing Rate of Diffusion ,\n Examples",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "Diffusion Types , Factors Influencing Rate of Diffusion ,\n Examples"
      },
      {
        "id": "batch-prarambh-2026_ev_31",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 32,
        "dateRaw": "Saturday, November 14, 2026",
        "isoDate": "2026-11-14",
        "dayName": "Saturday",
        "monthName": "November",
        "dayNumber": 14,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Carbohydrate Chemistry",
        "topic": "Classification , Monosaccharides , Disaccharides",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Classification , Monosaccharides , Disaccharides"
      },
      {
        "id": "batch-prarambh-2026_ev_32",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 33,
        "dateRaw": "Sunday, November 15, 2026",
        "isoDate": "2026-11-15",
        "dayName": "Sunday",
        "monthName": "November",
        "dayNumber": 15,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      },
      {
        "id": "batch-prarambh-2026_ev_33",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 34,
        "dateRaw": "Monday, November 16, 2026",
        "isoDate": "2026-11-16",
        "dayName": "Monday",
        "monthName": "November",
        "dayNumber": 16,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "Transport processes",
        "topic": "Active Transport , \nPrimary And Secondary Active Transports , \nNa+/K+ Pump , Abc Transporters",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "Active Transport , \nPrimary And Secondary Active Transports , \nNa+/K+ Pump , Abc Transporters"
      },
      {
        "id": "batch-prarambh-2026_ev_34",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 35,
        "dateRaw": "Tuesday, November 17, 2026",
        "isoDate": "2026-11-17",
        "dayName": "Tuesday",
        "monthName": "November",
        "dayNumber": 17,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "SUPERIOR EXTREMITY",
        "topic": "Bones of Upper limb - Part 1",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Bones of Upper limb - Part 1"
      },
      {
        "id": "batch-prarambh-2026_ev_35",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 36,
        "dateRaw": "Wednesday, November 18, 2026",
        "isoDate": "2026-11-18",
        "dayName": "Wednesday",
        "monthName": "November",
        "dayNumber": 18,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Carbohydrate Chemistry",
        "topic": "Homopolysaccharides , Gags",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Homopolysaccharides , Gags"
      },
      {
        "id": "batch-prarambh-2026_ev_36",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 37,
        "dateRaw": "Thursday, November 19, 2026",
        "isoDate": "2026-11-19",
        "dayName": "Thursday",
        "monthName": "November",
        "dayNumber": 19,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "SUPERIOR EXTREMITY",
        "topic": "Axilla",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Axilla"
      },
      {
        "id": "batch-prarambh-2026_ev_37",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 38,
        "dateRaw": "Friday, November 20, 2026",
        "isoDate": "2026-11-20",
        "dayName": "Friday",
        "monthName": "November",
        "dayNumber": 20,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "RMP",
        "topic": "Equilibrium Potential , Nernest Equation , \nGoldmann'S Constant Field Equation , \nContribution of K+ Pump",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "Equilibrium Potential , Nernest Equation , \nGoldmann'S Constant Field Equation , \nContribution of K+ Pump"
      },
      {
        "id": "batch-prarambh-2026_ev_38",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 39,
        "dateRaw": "Saturday, November 21, 2026",
        "isoDate": "2026-11-21",
        "dayName": "Saturday",
        "monthName": "November",
        "dayNumber": 21,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Lipid Chemistry",
        "topic": "Definition And Classification , Phospholipids",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Definition And Classification , Phospholipids"
      },
      {
        "id": "batch-prarambh-2026_ev_39",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 40,
        "dateRaw": "Sunday, November 22, 2026",
        "isoDate": "2026-11-22",
        "dayName": "Sunday",
        "monthName": "November",
        "dayNumber": 22,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      },
      {
        "id": "batch-prarambh-2026_ev_40",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 41,
        "dateRaw": "Monday, November 23, 2026",
        "isoDate": "2026-11-23",
        "dayName": "Monday",
        "monthName": "November",
        "dayNumber": 23,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "RMP",
        "topic": "Goldmann'S Constant Field Equation , \nContribution By Na+/K+ Pump",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "Goldmann'S Constant Field Equation , \nContribution By Na+/K+ Pump"
      },
      {
        "id": "batch-prarambh-2026_ev_41",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 42,
        "dateRaw": "Tuesday, November 24, 2026",
        "isoDate": "2026-11-24",
        "dayName": "Tuesday",
        "monthName": "November",
        "dayNumber": 24,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "SUPERIOR EXTREMITY",
        "topic": "The Brachial Plexus",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "The Brachial Plexus"
      },
      {
        "id": "batch-prarambh-2026_ev_42",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 43,
        "dateRaw": "Wednesday, November 25, 2026",
        "isoDate": "2026-11-25",
        "dayName": "Wednesday",
        "monthName": "November",
        "dayNumber": 25,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Lipid Chemistry",
        "topic": "Glycolipids, Eicosanoids, EFA",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Glycolipids, Eicosanoids, EFA"
      },
      {
        "id": "batch-prarambh-2026_ev_43",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 44,
        "dateRaw": "Thursday, November 26, 2026",
        "isoDate": "2026-11-26",
        "dayName": "Thursday",
        "monthName": "November",
        "dayNumber": 26,
        "year": 2026,
        "faculty": "Dr. Pradeep Pawar",
        "subject": "Anatomy",
        "chapter": "SUPERIOR EXTREMITY",
        "topic": "Front of Arm & Cubital Fossa",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Front of Arm & Cubital Fossa"
      },
      {
        "id": "batch-prarambh-2026_ev_44",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 45,
        "dateRaw": "Friday, November 27, 2026",
        "isoDate": "2026-11-27",
        "dayName": "Friday",
        "monthName": "November",
        "dayNumber": 27,
        "year": 2026,
        "faculty": "Dr. Vivek Nalgirkar",
        "subject": "Physiology",
        "chapter": "Action Potential",
        "topic": "Stimulus, Membrane Excitation",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 150,
        "timings": "6:30pm to 9:00pm",
        "startTime": "6:30pm",
        "endTime": "9:00pm",
        "startHour": 18.5,
        "eventType": "class",
        "displayTitle": "Stimulus, Membrane Excitation"
      },
      {
        "id": "batch-prarambh-2026_ev_45",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 46,
        "dateRaw": "Saturday, November 28, 2026",
        "isoDate": "2026-11-28",
        "dayName": "Saturday",
        "monthName": "November",
        "dayNumber": 28,
        "year": 2026,
        "faculty": "Dr. Rajesh Jambhulkar",
        "subject": "Biochemistry",
        "chapter": "Lipid Chemistry",
        "topic": "Lipoproteins, Lipid Profile, Cholesterol",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "7:00pm to 9:00pm",
        "startTime": "7:00pm",
        "endTime": "9:00pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Lipoproteins, Lipid Profile, Cholesterol"
      },
      {
        "id": "batch-prarambh-2026_ev_46",
        "batchId": "batch-prarambh-2026",
        "batchName": "Prarambh 2026 Batch for MBBS 1st Year",
        "rowIndex": 47,
        "dateRaw": "Sunday, November 29, 2026",
        "isoDate": "2026-11-29",
        "dayName": "Sunday",
        "monthName": "November",
        "dayNumber": 29,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      }
    ]
  },
  {
    "id": "batch-sushruta-2026",
    "name": "Sushruta 2026 Batch for MBBS 3rd Year",
    "subtitle": "Live on PW MedEd APP",
    "sourceUrl": "https://docs.google.com/spreadsheets/d/1ccYTSQgcGdEEq0Jlaxw3Kt-ScB4O-XLJg4LNQCmJvUU/edit?gid=1107483760#gid=1107483760",
    "gid": "1107483760",
    "sheetTabName": "Lecture Planner",
    "lastSynced": "2026-09-14T11:29:06.643Z",
    "eventCount": 46,
    "events": [
      {
        "id": "batch-sushruta-2026_ev_1",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 2,
        "dateRaw": "Thursday, October 15, 2026",
        "isoDate": "2026-10-15",
        "dayName": "Thursday",
        "monthName": "October",
        "dayNumber": 15,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Introduction to Community Medicine",
        "topic": "Introduction and Orientation- Community Medicine",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Introduction and Orientation- Community Medicine"
      },
      {
        "id": "batch-sushruta-2026_ev_2",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 3,
        "dateRaw": "Friday, October 16, 2026",
        "isoDate": "2026-10-16",
        "dayName": "Friday",
        "monthName": "October",
        "dayNumber": 16,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Introduction to Community Medicine",
        "topic": "Introduction and Orientation- Community Medicine",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Introduction and Orientation- Community Medicine"
      },
      {
        "id": "batch-sushruta-2026_ev_3",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 4,
        "dateRaw": "Saturday, October 17, 2026",
        "isoDate": "2026-10-17",
        "dayName": "Saturday",
        "monthName": "October",
        "dayNumber": 17,
        "year": 2026,
        "faculty": "Dr. Sudha Ma'am",
        "subject": "Ophthalmology",
        "chapter": "Oriention to Ophthalmology",
        "topic": "Oriention to Ophthalmology",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Oriention to Ophthalmology"
      },
      {
        "id": "batch-sushruta-2026_ev_4",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 5,
        "dateRaw": "Sunday, October 18, 2026",
        "isoDate": "2026-10-18",
        "dayName": "Sunday",
        "monthName": "October",
        "dayNumber": 18,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      },
      {
        "id": "batch-sushruta-2026_ev_5",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 6,
        "dateRaw": "Monday, October 19, 2026",
        "isoDate": "2026-10-19",
        "dayName": "Monday",
        "monthName": "October",
        "dayNumber": 19,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Principles of epidemiology and epidemiological methods",
        "topic": "Epidemiological studies, cross sectional, ecological and case control",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Epidemiological studies, cross sectional, ecological and case control"
      },
      {
        "id": "batch-sushruta-2026_ev_6",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 7,
        "dateRaw": "Tuesday, October 20, 2026",
        "isoDate": "2026-10-20",
        "dayName": "Tuesday",
        "monthName": "October",
        "dayNumber": 20,
        "year": 2026,
        "faculty": "Dr. Manjunath Sir",
        "subject": "FMT",
        "chapter": "Introduction to Forensic Medicine",
        "topic": "Introduction to Forensic Medicine\nLegal Procedure - Part 1",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Introduction to Forensic Medicine\nLegal Procedure - Part 1"
      },
      {
        "id": "batch-sushruta-2026_ev_7",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 8,
        "dateRaw": "Wednesday, October 21, 2026",
        "isoDate": "2026-10-21",
        "dayName": "Wednesday",
        "monthName": "October",
        "dayNumber": 21,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Ear",
        "topic": "Anatomy of External Ear",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Anatomy of External Ear"
      },
      {
        "id": "batch-sushruta-2026_ev_8",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 9,
        "dateRaw": "Thursday, October 22, 2026",
        "isoDate": "2026-10-22",
        "dayName": "Thursday",
        "monthName": "October",
        "dayNumber": 22,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Principles of epidemiology and epidemiological methods",
        "topic": "3 Types of Cohort studies, RR,AR and PAR and RCT",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "3 Types of Cohort studies, RR,AR and PAR and RCT"
      },
      {
        "id": "batch-sushruta-2026_ev_9",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 10,
        "dateRaw": "Friday, October 23, 2026",
        "isoDate": "2026-10-23",
        "dayName": "Friday",
        "monthName": "October",
        "dayNumber": 23,
        "year": 2026,
        "faculty": "Dr. Sudha Ma'am",
        "subject": "Ophthalmology",
        "chapter": "Ophthalmology Basics",
        "topic": "Coats and Contents of Eyeball",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Coats and Contents of Eyeball"
      },
      {
        "id": "batch-sushruta-2026_ev_10",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 11,
        "dateRaw": "Saturday, October 24, 2026",
        "isoDate": "2026-10-24",
        "dayName": "Saturday",
        "monthName": "October",
        "dayNumber": 24,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Ear",
        "topic": "Anatomy of Middle Ear",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Anatomy of Middle Ear"
      },
      {
        "id": "batch-sushruta-2026_ev_11",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 12,
        "dateRaw": "Sunday, October 25, 2026",
        "isoDate": "2026-10-25",
        "dayName": "Sunday",
        "monthName": "October",
        "dayNumber": 25,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      },
      {
        "id": "batch-sushruta-2026_ev_12",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 13,
        "dateRaw": "Monday, October 26, 2026",
        "isoDate": "2026-10-26",
        "dayName": "Monday",
        "monthName": "October",
        "dayNumber": 26,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Principles of epidemiology and epidemiological methods",
        "topic": "Meta Analysis and Systematic Review, Evidence Based Medicine, \nHills Criteria of Association",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Meta Analysis and Systematic Review, Evidence Based Medicine, \nHills Criteria of Association"
      },
      {
        "id": "batch-sushruta-2026_ev_13",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 14,
        "dateRaw": "Tuesday, October 27, 2026",
        "isoDate": "2026-10-27",
        "dayName": "Tuesday",
        "monthName": "October",
        "dayNumber": 27,
        "year": 2026,
        "faculty": "Dr. Manjunath Sir",
        "subject": "FMT",
        "chapter": "Legal Procedure",
        "topic": "Legal Procedure - Part 2",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Legal Procedure - Part 2"
      },
      {
        "id": "batch-sushruta-2026_ev_14",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 15,
        "dateRaw": "Wednesday, October 28, 2026",
        "isoDate": "2026-10-28",
        "dayName": "Wednesday",
        "monthName": "October",
        "dayNumber": 28,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Ear",
        "topic": "Tympanic Membrane",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Tympanic Membrane"
      },
      {
        "id": "batch-sushruta-2026_ev_15",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 16,
        "dateRaw": "Thursday, October 29, 2026",
        "isoDate": "2026-10-29",
        "dayName": "Thursday",
        "monthName": "October",
        "dayNumber": 29,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Principles of epidemiology and epidemiological methods",
        "topic": "Different Types of Biases And How To Prevent It, \nValidity And Reliability, Random And Systematic Errors",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Different Types of Biases And How To Prevent It, \nValidity And Reliability, Random And Systematic Errors"
      },
      {
        "id": "batch-sushruta-2026_ev_16",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 17,
        "dateRaw": "Friday, October 30, 2026",
        "isoDate": "2026-10-30",
        "dayName": "Friday",
        "monthName": "October",
        "dayNumber": 30,
        "year": 2026,
        "faculty": "Dr. Sudha Ma'am",
        "subject": "Ophthalmology",
        "chapter": "Ophthalmology Basics",
        "topic": "Clinical Examination - Part 1",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Clinical Examination - Part 1"
      },
      {
        "id": "batch-sushruta-2026_ev_17",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 18,
        "dateRaw": "Saturday, October 31, 2026",
        "isoDate": "2026-10-31",
        "dayName": "Saturday",
        "monthName": "October",
        "dayNumber": 31,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Ear",
        "topic": "Anatomy of Inner Ear",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Anatomy of Inner Ear"
      },
      {
        "id": "batch-sushruta-2026_ev_18",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 19,
        "dateRaw": "Sunday, November 1, 2026",
        "isoDate": "2026-11-01",
        "dayName": "Sunday",
        "monthName": "November",
        "dayNumber": 1,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      },
      {
        "id": "batch-sushruta-2026_ev_19",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 20,
        "dateRaw": "Monday, November 2, 2026",
        "isoDate": "2026-11-02",
        "dayName": "Monday",
        "monthName": "November",
        "dayNumber": 2,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Principles of epidemiology and epidemiological methods",
        "topic": "Lead Time Bias , Kaplein Meir Plot",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Lead Time Bias , Kaplein Meir Plot"
      },
      {
        "id": "batch-sushruta-2026_ev_20",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 21,
        "dateRaw": "Tuesday, November 3, 2026",
        "isoDate": "2026-11-03",
        "dayName": "Tuesday",
        "monthName": "November",
        "dayNumber": 3,
        "year": 2026,
        "faculty": "Dr. Manjunath Sir",
        "subject": "FMT",
        "chapter": "Medical Law and Ethics",
        "topic": "Medical Law and Ethics -  Part 1",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Medical Law and Ethics -  Part 1"
      },
      {
        "id": "batch-sushruta-2026_ev_21",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 22,
        "dateRaw": "Wednesday, November 4, 2026",
        "isoDate": "2026-11-04",
        "dayName": "Wednesday",
        "monthName": "November",
        "dayNumber": 4,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Ear",
        "topic": "Physiology of Hearing",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Physiology of Hearing"
      },
      {
        "id": "batch-sushruta-2026_ev_22",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 23,
        "dateRaw": "Thursday, November 5, 2026",
        "isoDate": "2026-11-05",
        "dayName": "Thursday",
        "monthName": "November",
        "dayNumber": 5,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Principles of epidemiology and epidemiological methods",
        "topic": "Levels of prevention",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Levels of prevention"
      },
      {
        "id": "batch-sushruta-2026_ev_23",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 24,
        "dateRaw": "Friday, November 6, 2026",
        "isoDate": "2026-11-06",
        "dayName": "Friday",
        "monthName": "November",
        "dayNumber": 6,
        "year": 2026,
        "faculty": "Dr. Sudha Ma'am",
        "subject": "Ophthalmology",
        "chapter": "Ophthalmology Basics",
        "topic": "Clinical Examination - Part 2",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Clinical Examination - Part 2"
      },
      {
        "id": "batch-sushruta-2026_ev_24",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 25,
        "dateRaw": "Saturday, November 7, 2026",
        "isoDate": "2026-11-07",
        "dayName": "Saturday",
        "monthName": "November",
        "dayNumber": 7,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Ear",
        "topic": "Physiology of Equilibrium",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Physiology of Equilibrium"
      },
      {
        "id": "batch-sushruta-2026_ev_25",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 26,
        "dateRaw": "Sunday, November 8, 2026",
        "isoDate": "2026-11-08",
        "dayName": "Sunday",
        "monthName": "November",
        "dayNumber": 8,
        "year": 2026,
        "faculty": "Diwali Holidays",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "holiday",
        "displayTitle": "Diwali Holidays"
      },
      {
        "id": "batch-sushruta-2026_ev_26",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 27,
        "dateRaw": "Monday, November 9, 2026",
        "isoDate": "2026-11-09",
        "dayName": "Monday",
        "monthName": "November",
        "dayNumber": 9,
        "year": 2026,
        "faculty": "",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "holiday",
        "displayTitle": "Holiday"
      },
      {
        "id": "batch-sushruta-2026_ev_27",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 28,
        "dateRaw": "Tuesday, November 10, 2026",
        "isoDate": "2026-11-10",
        "dayName": "Tuesday",
        "monthName": "November",
        "dayNumber": 10,
        "year": 2026,
        "faculty": "",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "holiday",
        "displayTitle": "Holiday"
      },
      {
        "id": "batch-sushruta-2026_ev_28",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 29,
        "dateRaw": "Wednesday, November 11, 2026",
        "isoDate": "2026-11-11",
        "dayName": "Wednesday",
        "monthName": "November",
        "dayNumber": 11,
        "year": 2026,
        "faculty": "",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "holiday",
        "displayTitle": "Holiday"
      },
      {
        "id": "batch-sushruta-2026_ev_29",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 30,
        "dateRaw": "Thursday, November 12, 2026",
        "isoDate": "2026-11-12",
        "dayName": "Thursday",
        "monthName": "November",
        "dayNumber": 12,
        "year": 2026,
        "faculty": "Dr. Manjunath Sir",
        "subject": "FMT",
        "chapter": "Medical Law and Ethics",
        "topic": "Medical Law and Ethics -  Part 2",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Medical Law and Ethics -  Part 2"
      },
      {
        "id": "batch-sushruta-2026_ev_30",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 31,
        "dateRaw": "Friday, November 13, 2026",
        "isoDate": "2026-11-13",
        "dayName": "Friday",
        "monthName": "November",
        "dayNumber": 13,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Principles of epidemiology and epidemiological methods",
        "topic": "Direct And Indirect Standarization, Morbidity Indicators",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Direct And Indirect Standarization, Morbidity Indicators"
      },
      {
        "id": "batch-sushruta-2026_ev_31",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 32,
        "dateRaw": "Saturday, November 14, 2026",
        "isoDate": "2026-11-14",
        "dayName": "Saturday",
        "monthName": "November",
        "dayNumber": 14,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Ear",
        "topic": "Pure Tone Audiometry",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Pure Tone Audiometry"
      },
      {
        "id": "batch-sushruta-2026_ev_32",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 33,
        "dateRaw": "Sunday, November 15, 2026",
        "isoDate": "2026-11-15",
        "dayName": "Sunday",
        "monthName": "November",
        "dayNumber": 15,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      },
      {
        "id": "batch-sushruta-2026_ev_33",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 34,
        "dateRaw": "Monday, November 16, 2026",
        "isoDate": "2026-11-16",
        "dayName": "Monday",
        "monthName": "November",
        "dayNumber": 16,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Principles of epidemiology and epidemiological methods",
        "topic": "Epidemics,Levels of Prevention",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Epidemics,Levels of Prevention"
      },
      {
        "id": "batch-sushruta-2026_ev_34",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 35,
        "dateRaw": "Tuesday, November 17, 2026",
        "isoDate": "2026-11-17",
        "dayName": "Tuesday",
        "monthName": "November",
        "dayNumber": 17,
        "year": 2026,
        "faculty": "Dr. Manjunath Sir",
        "subject": "FMT",
        "chapter": "Medical Law and Ethics",
        "topic": "Medical Law and Ethics -  Part 3",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Medical Law and Ethics -  Part 3"
      },
      {
        "id": "batch-sushruta-2026_ev_35",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 36,
        "dateRaw": "Wednesday, November 18, 2026",
        "isoDate": "2026-11-18",
        "dayName": "Wednesday",
        "monthName": "November",
        "dayNumber": 18,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Ear",
        "topic": "Impedance Audiometry And Oae",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Impedance Audiometry And Oae"
      },
      {
        "id": "batch-sushruta-2026_ev_36",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 37,
        "dateRaw": "Thursday, November 19, 2026",
        "isoDate": "2026-11-19",
        "dayName": "Thursday",
        "monthName": "November",
        "dayNumber": 19,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Communicable Diease",
        "topic": "Communicable Diseases",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Communicable Diseases"
      },
      {
        "id": "batch-sushruta-2026_ev_37",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 38,
        "dateRaw": "Friday, November 20, 2026",
        "isoDate": "2026-11-20",
        "dayName": "Friday",
        "monthName": "November",
        "dayNumber": 20,
        "year": 2026,
        "faculty": "Dr. Sudha Ma'am",
        "subject": "Ophthalmology",
        "chapter": "Refraction",
        "topic": "Basics of Refraction",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Basics of Refraction"
      },
      {
        "id": "batch-sushruta-2026_ev_38",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 39,
        "dateRaw": "Saturday, November 21, 2026",
        "isoDate": "2026-11-21",
        "dayName": "Saturday",
        "monthName": "November",
        "dayNumber": 21,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Ear",
        "topic": "Bera",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Bera"
      },
      {
        "id": "batch-sushruta-2026_ev_39",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 40,
        "dateRaw": "Sunday, November 22, 2026",
        "isoDate": "2026-11-22",
        "dayName": "Sunday",
        "monthName": "November",
        "dayNumber": 22,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      },
      {
        "id": "batch-sushruta-2026_ev_40",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 41,
        "dateRaw": "Monday, November 23, 2026",
        "isoDate": "2026-11-23",
        "dayName": "Monday",
        "monthName": "November",
        "dayNumber": 23,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Communicable Diease",
        "topic": "Non Communicable Diseases",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Non Communicable Diseases"
      },
      {
        "id": "batch-sushruta-2026_ev_41",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 42,
        "dateRaw": "Tuesday, November 24, 2026",
        "isoDate": "2026-11-24",
        "dayName": "Tuesday",
        "monthName": "November",
        "dayNumber": 24,
        "year": 2026,
        "faculty": "Dr. Manjunath Sir",
        "subject": "FMT",
        "chapter": "Thanatology",
        "topic": "Thanatology -I",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Thanatology -I"
      },
      {
        "id": "batch-sushruta-2026_ev_42",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 43,
        "dateRaw": "Wednesday, November 25, 2026",
        "isoDate": "2026-11-25",
        "dayName": "Wednesday",
        "monthName": "November",
        "dayNumber": 25,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Ear",
        "topic": "Malignant Otitis Externa",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Malignant Otitis Externa"
      },
      {
        "id": "batch-sushruta-2026_ev_43",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 44,
        "dateRaw": "Thursday, November 26, 2026",
        "isoDate": "2026-11-26",
        "dayName": "Thursday",
        "monthName": "November",
        "dayNumber": 26,
        "year": 2026,
        "faculty": "Dr. Ashwani Sir",
        "subject": "Community Medicine",
        "chapter": "Communicable Diease",
        "topic": "Non Communicable Diseases",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Non Communicable Diseases"
      },
      {
        "id": "batch-sushruta-2026_ev_44",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 45,
        "dateRaw": "Friday, November 27, 2026",
        "isoDate": "2026-11-27",
        "dayName": "Friday",
        "monthName": "November",
        "dayNumber": 27,
        "year": 2026,
        "faculty": "Dr. Sudha Ma'am",
        "subject": "Ophthalmology",
        "chapter": "Refraction",
        "topic": "Refractive Errors",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Refractive Errors"
      },
      {
        "id": "batch-sushruta-2026_ev_45",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 46,
        "dateRaw": "Saturday, November 28, 2026",
        "isoDate": "2026-11-28",
        "dayName": "Saturday",
        "monthName": "November",
        "dayNumber": 28,
        "year": 2026,
        "faculty": "Dr. Sanchit Sir",
        "subject": "ENT",
        "chapter": "Ear",
        "topic": "Diseases of Pinna",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 90,
        "timings": "7:00pm to 8:30pm",
        "startTime": "7:00pm",
        "endTime": "8:30pm",
        "startHour": 19,
        "eventType": "class",
        "displayTitle": "Diseases of Pinna"
      },
      {
        "id": "batch-sushruta-2026_ev_46",
        "batchId": "batch-sushruta-2026",
        "batchName": "Sushruta 2026 Batch for MBBS 3rd Year",
        "rowIndex": 47,
        "dateRaw": "Sunday, November 29, 2026",
        "isoDate": "2026-11-29",
        "dayName": "Sunday",
        "monthName": "November",
        "dayNumber": 29,
        "year": 2026,
        "faculty": "COOL OFF",
        "subject": "",
        "chapter": "",
        "topic": "",
        "noLectures": "1",
        "duration": "2 Hours",
        "durationMinutes": 120,
        "timings": "",
        "startTime": "",
        "endTime": "",
        "startHour": 19,
        "eventType": "cool_off",
        "displayTitle": "COOL OFF"
      }
    ]
  }
];
